"""add vendor to task

Revision ID: 0028d4b6fc25
Revises: a90cffb6d8cd
Create Date: 2025-06-23 23:59:43.777891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0028d4b6fc25'
down_revision: Union[str, None] = 'a90cffb6d8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('vendor_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_tasks', 'vendor_code')
    # ### end Alembic commands ###
