"""add_aspects_field_to_feedbacks

Revision ID: 01e45178cb5b
Revises: 11282254ebeb
Create Date: 2025-08-10 18:21:41.536239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e45178cb5b'
down_revision: Union[str, None] = '11282254ebeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('feedback_analytics', 'article',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.add_column('feedbacks', sa.Column('aspects', sa.JSON(), nullable=True))
    op.alter_column('feedbacks', 'article',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('scheduled_tasks', 'nm_id',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='nm_id::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduled_tasks', 'nm_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('feedbacks', 'article',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.drop_column('feedbacks', 'aspects')
    op.alter_column('feedback_analytics', 'article',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
