"""add imagebb_key to user

Revision ID: 01fe49623cb0
Revises: 8138ed8c4c73
Create Date: 2025-06-28 14:54:04.130840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01fe49623cb0'
down_revision: Union[str, None] = '8138ed8c4c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('imagebb_key', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'imagebb_key')
    # ### end Alembic commands ###
