"""update wb_api_key

Revision ID: 14ca554c448b
Revises: 698b28ca5c1b
Create Date: 2025-06-21 00:45:10.351994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14ca554c448b'
down_revision: Union[str, None] = '698b28ca5c1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')

    # Исправленная команда для изменения типа с явным USING
    op.alter_column('users', 'wb_api_key',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSON(),
               existing_nullable=True,
               postgresql_using='wb_api_key::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'wb_api_key',
               existing_type=postgresql.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               postgresql_using='wb_api_key::text')

    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('managed_brands', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('admins_pkey')),
    sa.UniqueConstraint('email', name=op.f('admins_email_key'))
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    # ### end Alembic commands ###