"""add_feedback_top_tracking_table

Revision ID: 28a729b6346d
Revises: 40168fd83303
Create Date: 2025-08-19 21:48:38.888165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28a729b6346d'
down_revision: Union[str, None] = '40168fd83303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_top_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=32), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entered_top_1_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entered_top_3_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entered_top_5_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entered_top_10_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_top_1_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_top_3_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_top_5_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_top_10_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_in_top_1', sa.Integer(), nullable=True),
    sa.Column('time_in_top_3', sa.Integer(), nullable=True),
    sa.Column('time_in_top_5', sa.Integer(), nullable=True),
    sa.Column('time_in_top_10', sa.Integer(), nullable=True),
    sa.Column('is_in_top_1', sa.Boolean(), nullable=True),
    sa.Column('is_in_top_3', sa.Boolean(), nullable=True),
    sa.Column('is_in_top_5', sa.Boolean(), nullable=True),
    sa.Column('is_in_top_10', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_article_brand_user', 'feedback_top_tracking', ['article', 'brand', 'user_id'], unique=False)
    op.create_index('idx_feedback_id', 'feedback_top_tracking', ['feedback_id'], unique=False)
    op.create_index('idx_is_in_tops', 'feedback_top_tracking', ['is_in_top_1', 'is_in_top_3', 'is_in_top_5', 'is_in_top_10'], unique=False)
    op.create_index(op.f('ix_feedback_top_tracking_article'), 'feedback_top_tracking', ['article'], unique=False)
    op.create_index(op.f('ix_feedback_top_tracking_brand'), 'feedback_top_tracking', ['brand'], unique=False)
    op.create_index(op.f('ix_feedback_top_tracking_feedback_id'), 'feedback_top_tracking', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_top_tracking_id'), 'feedback_top_tracking', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_top_tracking_user_id'), 'feedback_top_tracking', ['user_id'], unique=False)
    op.add_column('feedback_analytics', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_analytics', 'updated_at')
    op.drop_index(op.f('ix_feedback_top_tracking_user_id'), table_name='feedback_top_tracking')
    op.drop_index(op.f('ix_feedback_top_tracking_id'), table_name='feedback_top_tracking')
    op.drop_index(op.f('ix_feedback_top_tracking_feedback_id'), table_name='feedback_top_tracking')
    op.drop_index(op.f('ix_feedback_top_tracking_brand'), table_name='feedback_top_tracking')
    op.drop_index(op.f('ix_feedback_top_tracking_article'), table_name='feedback_top_tracking')
    op.drop_index('idx_is_in_tops', table_name='feedback_top_tracking')
    op.drop_index('idx_feedback_id', table_name='feedback_top_tracking')
    op.drop_index('idx_article_brand_user', table_name='feedback_top_tracking')
    op.drop_table('feedback_top_tracking')
    # ### end Alembic commands ###
