"""Add deleted_at field to Feedback model

Revision ID: 2fd81de6f86b
Revises: 6faef9c12b2e
Create Date: 2025-07-12 19:22:29.679480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fd81de6f86b'
down_revision: Union[str, None] = '6faef9c12b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'deleted_at')
    # ### end Alembic commands ###
