"""add_aspects_tables

Revision ID: 40168fd83303
Revises: 01e45178cb5b
Create Date: 2025-08-15 21:44:51.495459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40168fd83303'
down_revision: Union[str, None] = '01e45178cb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_base_aspect', sa.Boolean(), nullable=True),
    sa.Column('is_new_aspect', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_aspects_category', 'aspects', ['category'], unique=False)
    op.create_index('idx_aspects_is_base', 'aspects', ['is_base_aspect'], unique=False)
    op.create_index('idx_aspects_is_new', 'aspects', ['is_new_aspect'], unique=False)
    op.create_index('idx_aspects_usage_count', 'aspects', ['usage_count'], unique=False)
    op.create_index(op.f('ix_aspects_id'), 'aspects', ['id'], unique=False)
    op.create_index(op.f('ix_aspects_name'), 'aspects', ['name'], unique=True)
    op.create_table('feedback_aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.Column('aspect_name', sa.String(length=100), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('evidence_words', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_aspects_aspect_name', 'feedback_aspects', ['aspect_name'], unique=False)
    op.create_index('idx_feedback_aspects_feedback_id', 'feedback_aspects', ['feedback_id'], unique=False)
    op.create_index('idx_feedback_aspects_feedback_sentiment', 'feedback_aspects', ['feedback_id', 'sentiment'], unique=False)
    op.create_index('idx_feedback_aspects_sentiment', 'feedback_aspects', ['sentiment'], unique=False)
    op.create_index(op.f('ix_feedback_aspects_aspect_name'), 'feedback_aspects', ['aspect_name'], unique=False)
    op.create_index(op.f('ix_feedback_aspects_feedback_id'), 'feedback_aspects', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_feedback_aspects_id'), 'feedback_aspects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_aspects_id'), table_name='feedback_aspects')
    op.drop_index(op.f('ix_feedback_aspects_feedback_id'), table_name='feedback_aspects')
    op.drop_index(op.f('ix_feedback_aspects_aspect_name'), table_name='feedback_aspects')
    op.drop_index('idx_feedback_aspects_sentiment', table_name='feedback_aspects')
    op.drop_index('idx_feedback_aspects_feedback_sentiment', table_name='feedback_aspects')
    op.drop_index('idx_feedback_aspects_feedback_id', table_name='feedback_aspects')
    op.drop_index('idx_feedback_aspects_aspect_name', table_name='feedback_aspects')
    op.drop_table('feedback_aspects')
    op.drop_index(op.f('ix_aspects_name'), table_name='aspects')
    op.drop_index(op.f('ix_aspects_id'), table_name='aspects')
    op.drop_index('idx_aspects_usage_count', table_name='aspects')
    op.drop_index('idx_aspects_is_new', table_name='aspects')
    op.drop_index('idx_aspects_is_base', table_name='aspects')
    op.drop_index('idx_aspects_category', table_name='aspects')
    op.drop_table('aspects')
    # ### end Alembic commands ###
