"""add is_deleted to feedbacks

Revision ID: 43e9b25bd9f4
Revises: 1ec6fff6627b
Create Date: 2025-07-02 23:49:51.212344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e9b25bd9f4'
down_revision: Union[str, None] = '1ec6fff6627b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('feedbacks', 'is_deleted')
    # ### end Alembic commands ###
