"""add_feedback_tables

Revision ID: 7ed16b1e8537
Revises: 61ceffec475d
Create Date: 2025-07-01 01:03:39.456865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed16b1e8537'
down_revision: Union[str, None] = '61ceffec475d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('positive_count', sa.Integer(), nullable=True),
    sa.Column('neutral_count', sa.Integer(), nullable=True),
    sa.Column('negative_count', sa.Integer(), nullable=True),
    sa.Column('negative_reviews_count', sa.Integer(), nullable=True),
    sa.Column('processed_negative_count', sa.Integer(), nullable=True),
    sa.Column('unprocessed_negative_count', sa.Integer(), nullable=True),
    sa.Column('avg_sentiment', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_analytics_article'), 'feedback_analytics', ['article'], unique=False)
    op.create_index(op.f('ix_feedback_analytics_brand'), 'feedback_analytics', ['brand'], unique=False)
    op.create_index(op.f('ix_feedback_analytics_date'), 'feedback_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_feedback_analytics_id'), 'feedback_analytics', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('main_text', sa.Text(), nullable=True),
    sa.Column('pros_text', sa.Text(), nullable=True),
    sa.Column('cons_text', sa.Text(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_negative', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Integer(), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['history_id'], ['history.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_article'), 'feedbacks', ['article'], unique=False)
    op.create_index(op.f('ix_feedbacks_brand'), 'feedbacks', ['brand'], unique=False)
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_brand'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_article'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_feedback_analytics_id'), table_name='feedback_analytics')
    op.drop_index(op.f('ix_feedback_analytics_date'), table_name='feedback_analytics')
    op.drop_index(op.f('ix_feedback_analytics_brand'), table_name='feedback_analytics')
    op.drop_index(op.f('ix_feedback_analytics_article'), table_name='feedback_analytics')
    op.drop_table('feedback_analytics')
    # ### end Alembic commands ###
