"""add_index_to_is_deleted

Revision ID: a4adc8b72956
Revises: b76b57198e3d
Create Date: 2025-07-23 03:29:07.291700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4adc8b72956'
down_revision: Union[str, None] = 'b76b57198e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_feedbacks_is_deleted'), 'feedbacks', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_is_deleted'), table_name='feedbacks')
    # ### end Alembic commands ###
