"""delete vendor to task

Revision ID: e1f0a2ae3b08
Revises: 0028d4b6fc25
Create Date: 2025-06-24 00:05:45.192193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f0a2ae3b08'
down_revision: Union[str, None] = '0028d4b6fc25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_tasks', 'vendor_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_tasks', sa.Column('vendor_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
